### ISSUE TITLE
Technical design

### ISSUE THREAD

**Issue by ghost** [olgaialanskaia/Jamming#7]
> If authentication is successful, a user lands on a Jammming homepage where a Search Bar, a user Spotify profile image, and a Spotify-green color “Disconnect from Spotify” button are displayed.

Often times the best UI is the one with the least UI.

I like your idea to remove the SearchBar when the user is not connected. This should help better manage their expectations of what should happen in the natural workflow of the app.

Changing the green-button from "Connect" to "Disconnect" might be a little too subtle. Some users might totally miss that the text on the button changed and forget to disconnect. Perhaps turning the disconnect button would make it a little more full proof?

**Comment by olgaialanskaia** [comment]
@stevetoro Oh yeah I see your point. I was more thinking about to keep the color as a Spotify known for their green button colors. Should see if they have some button color for "logout" action. To make it "familiar" experience for the user.
